### ISSUE TITLE
ar30-exta的版本尚未更新至2017年版

### ISSUE THREAD

**Issue by yuanqiuye** [gontera/array30#1]
如題，不好意思費請更新檔案，謝謝您！

**Comment by gontera** [comment]
關於您的問題，謹答復如下：

1. 先前新增 CJK Ext-F 的部分，因非屬於本檔案收錄的字集範圍 (Ext-A)，故鍵碼表的部分沒有更新。
2. gcin Ext-A 版本的二級簡碼表，已於 2021/07/23 的釋出版本一併更新。
